### PR TITLE
fix(charts): fix charts with vega5

### PR DESCRIPTION
**Pull request by TomWBush**
I've made a quick fix to the pie chart. Few things to note below:
1. [vega-embed](https://github.com/vega/vega-embed#vega-embed) includes tooltip. So I removed ChartsPieChart.service.coffee:125. I'm not sure whether that mean we can completely get rid of vt in our project?
2. After some research, it seems like the specification format is for vega instead of vega-lite, since only vega has "marks", and vega-lite has "marks". But the properties of these two are quite different. So after changing the schema to vega, it starts working.
3. I believe most of the errors in graphs are caused by the vega/vega-lite mix-up that I mentioned in 2. So, if you agree with this change, I can proceed to fix the rest of the graphs.

### CODE REVIEW

**Comment by TomWBush** [comment]
I just pushed another style change. I've added two css rules to make the pie chart and the vega-bindings side by side, because the scrolling makes it very awkward to use on bigger screen. Below is the before and after comparison.
before
after

**Comment by alxndrkalinin** [comment]
Yep, that the issue. I didn't notice Pie [used vega](https://github.com/SOCR/SOCRAT/commit/d971ba5b92f41cde4813ed7155653e1ada38c2b7#diff-f811aa53ea513a5a4940a0e0351411ea551971c38dca3cdeca566f98db61a966L41) when I updated to vega-lite 5. Normal distribution chart has [the same issue](https://github.com/SOCR/SOCRAT/commit/d971ba5b92f41cde4813ed7155653e1ada38c2b7#diff-dc46251f8fa97f58b0579595abcaeaeec1637440a0d596d40430f6837ea60428L50), so you can fix that one too.
Controls on the side look good.

I also see changes to Area chart– were you able to test that one too?

**Comment by TomWBush** [comment]
Oh. I did not realize chartsareachart was the controller for a chart. I'll update it with the fix for all charts after I finish it tonight.

**Comment by alxndrkalinin** [comment]
Yea, it's a chart with at least [one temporal axis](https://vega.github.io/vega-lite/docs/area.html#area-chart). To test it, you can use Antarctic Ice Thickness Dataset and California Ozone Data from [SOCR Datasets](https://github.com/SOCR/SOCRAT/blob/dev/CONTRIBUTE.md#socr-datasets-for-testing`), as these datasets have dates.

**Comment by TomWBush** [comment]
Got it. And one issue unrelated to this PR is that I'm considering updating Jade to Pug 3, because Jade was renamed to Pug about 6 years ago.

**Comment by alxndrkalinin** [comment]
Feel free to update, but please test everything afterwards.

**Comment by TomWBush** [comment]
I've pushed a few more fixes. There are still 2 problems I think.
1.For parallel coordinates chart, ChartsList.service.coffee:237-239 does not have a vars property for the chart, which will cause an error in ChartsSidebarCtrl.controller.coffee.
2. My fix seems to got area chart running with no error, but it doesn't seem to work. I suspect the problem is also in ChartsSidebarCtrl.
And for these two charts, they both have error in console in the [deployed SOCRAT](http://nur-socr-web-dev02.miserver.it.umich.edu:3000/), so I guess the issues were not caused by the vega version upgrade.

**Comment by TomWBush** [comment]
I had some time looking into areachart today, and I found a general bug in parsing the xCols name for sidebar.
In ChartsSidebarCtrl.controller.coffee:191, when parsing date label, the code checks whether 3 random data of that column is integer or between 1900 and the current year. In the Antarctic Ice Thickness Dataset, there are two date columns, one of them is in this form "1-Apr-54', and the other is in this form "19540401". So you can see neither form satisfy the conditions.
I can think of two solutions:
1. Get rid of the year bound check.
2. Check data length, and parse the year to compare.

Which solution should I go with?

**Comment by TomWBush** [comment]
I spent some time looking into fixing parallel coordinate chart, but some variables in ChartsParallelCoordinates.service.coffee are confusing, particularly in the part where you reconstruct `datavals` using `data`. 
There are two variables labels and fields. But based on how you use it in the first for loop, fields also seem to be labels.
Also you seems to be iterating fields as an array but it's actually an object, so was that supposed to be another variable or the structure of `data` was changed but the parallel chart code wasn't changed accordingly?

**Review by alxndrkalinin — CHANGES_REQUESTED** [review]
For the `date` column format recognition, see code comment.

As for Parallel coordinates, the [current vega-lite example spec](https://vega.github.io/vega-lite/examples/parallel_coordinate.html) looks very different from we have there, so probably it's out of date. TBH, I don't recall all details of reformatting data for this chart, but `fields` seems to be an array, as `data` is array of arrays (data table) and calling [`data.splice(0, 1)[0]`](https://github.com/SOCR/SOCRAT/blob/master/app/scripts/analysis/Charts/ChartsParallelCoordinates.service.coffee#L29) returns the first row of that table.
Anyway, it's probably need to be re-implemented for the current spec.

**Comment by alxndrkalinin** [comment]
Merged as is for now.

**Pull request merged**
