### PR TITLE
Improves styling on normal distribution chart 

### PR DESCRIPTION
**Pull request by acell**
- makes line less bold
- has y-axis labels not intersect with x-axis
- also the y-axis labels are a teeny bit smaller so they do not look bigger than the x-axis labels

addresses SOCRAT-ISSUES #67 ( @ https://github.com/SOCR/SOCRAT-issues/issues/67 )

screen shot 2017-02-08 at 10 48 00 pm

### CODE REVIEW

**Comment by alxndrkalinin** [comment]
@acell this looks better

- can we remove outline at all?
- please follow our [commit message format](https://github.com/SOCR/SOCRAT/blob/master/CONTRIBUTE.md#commit-message-format) for all commits to SOCRAT

**Comment by acell** [comment]
@alxndrkalinin 
the outline for what? the normal distribution curve? yes, I can take that off

my bad, too excited about committing to recall the format--I will follow it / after making it so the curve has no outline?

**Comment by alxndrkalinin** [comment]
@acell yes, the distribution curve

**Comment by acell** [comment]
@alxndrkalinin 
OK yes then my second commit changed that 
screen shot 2017-02-09 at 12 48 24 pm

**Comment by alxndrkalinin** [comment]
@acell merged

**Pull request merged**
