### PR TITLE
chore(package.json): update package version

### PR DESCRIPTION
**Pull request by TomWBush**
Newer version of the following two packages are required to successfully run `npm install`
coffeescript@>= 2.0.0 needed for coffee-loader@2.0.0. So bump coffeescript from 1.10.0 to 2.0.0.
webpack@^1.1.0 || ^2 || ^2.1.0-beta || ^2.2.0-rc needed for karma-webpack@1.8.1. So bump karma-webpack from 1.2.2 to 5.0.0.

### CODE REVIEW

**Comment by alxndrkalinin** [comment]
I just quickly tried applying this patch and running `npm install` and the table in Data Input stopped working and there are errors in console. Did you test the app? Errors need to be fixed before merging.

**Comment by TomWBush** [comment]
After google search, I found it's because coffeescript 2.0.0 introduced some major syntax updates. So, I've decided to restore coffeescript to 1.10.0, and coffee-loader to 0.9.0, since this might be a huge task updating all the coffee files. I'm currently working on migrating glyphicon to fontawesome, and I'm also not on the MDP team this year. So, if I have time in the future, I might work on upgrading coffee to 2.0.0.

**Comment by alxndrkalinin** [comment]
I just pushed a quick fix for glyphicons to `dev`, not sure it's worth migrating to fontawesome. 

In general, `npm install` give many warnings, but unless it's breaking the app, we can ignore them for a while. For example, the app works fine with either `0.9.0` or `2.0.0` versions of `coffee-loader`. So it doesn't really make the difference to switch between them.

Good contribution would be fixing pie, normal, and heatmap charts that broke when vega-lite was updated to v5.

**Comment by TomWBush** [comment]
Yes, I saw the glyphicon fix. But we still need to upgrade karma-webpack to 5.0.0 as it is required by webpack 5.0.0. And coffee-loader also has to be < 1.0.0 as it's required by our coffeescript@1.12.7.
Have you tried doing a clean install by removing node_module and package-lock.json first? I think that is why you are not seeing the dependency errors.

**Comment by TomWBush** [comment]
And for glyphicons, it is removed in bootstrap 4. But since we are still using 3, I guess there is no need to migrating to fa then unless they change the dependency in the future.

**Comment by alxndrkalinin** [comment]
> Have you tried doing a clean install by removing node_module and package-lock.json first? I think that is why you are not seeing the dependency errors.

Yes, I do that after every commit to `package.json`. No errors now on the current `dev`, only warnings. Did you try updating your Node.js version?

**Comment by alxndrkalinin** [comment]
Screen Shot 2021-03-02 at 1 58 47 PM

I only get warnings from the clean install. Try clean install: remove SOCRAT, git clone -> switch to `dev` -> `npm install`

**Comment by alxndrkalinin** [comment]
> And for glyphicons, it is removed in bootstrap 4. But since we are still using 3, I guess there is no need to migrating to fa then unless they change the dependency in the future.

If you'd like, you can migrate to bootstrap 4, I don't really have the capacity right now.

**Comment by TomWBush** [comment]
Hmm that's very strange. I did the exact same thing by cloning the upstream dev branch. And run npm install. Here is one of the error.

**Comment by alxndrkalinin** [comment]
What version of Node/npm you're running?

**Comment by TomWBush** [comment]
I'm running 7.5.3.

**Comment by alxndrkalinin** [comment]
I reproduced it, seems like npm v7 issue, probably due to new [automatic peer dependency installation](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies).

LGTM to merge

**Comment by TomWBush** [comment]
Got it. I'll find time to work on fixing vega, or urge students in MDP this year to do it.

**Pull request merged**
