### PR TITLE
WIP refactor(charts): update bar and bubble chart

### PR DESCRIPTION
**Pull request by appletreeisyellow**

### CODE REVIEW

**Comment by alxndrkalinin** [comment]
@appletreeisyellow there are some issues, see my [comments](https://docs.google.com/document/d/1IwhbbuSdzdnS5d1CV1Sf40zgvIrFK5LVLhV8xgfVTcI/edit?usp=sharing)

**Comment by alxndrkalinin** [comment]
@appletreeisyellow looks better now! see few more comments in the [doc](https://docs.google.com/document/d/1IwhbbuSdzdnS5d1CV1Sf40zgvIrFK5LVLhV8xgfVTcI/edit?usp=sharing)

**Comment by alxndrkalinin** [comment]
@appletreeisyellow 

- [ ] legend for Radius in bubble is missing - impossible to say which is which
- [ ] d3's ordinal scale should be used to get Radius sizes, you can use [rangePoints](https://github.com/d3/d3-3.x-api-reference/blob/master/Ordinal-Scales.md#ordinal_rangePoints) for (min, max) radii

**Comment by appletreeisyellow** [comment]
There is no legend for Radius in Bubble chart. It has tooltip on each circle

**Comment by alxndrkalinin** [comment]
merged in e26dea68e5ba8d2f64bf650274a3d14c6eb93d0c

**Pull request closed without merging**
