### PR TITLE
refactor(app): Consistent UI #177

### PR DESCRIPTION
**Pull request by chartotu19**
https://github.com/SOCR/SOCRAT-issues/issues/177

### CODE REVIEW

**Comment by alxndrkalinin** [comment]
@chartotu19 can you merge from/rebase on current `dev` branch and test? if I pull these changes, they brake GetData:

screen shot 2017-03-30 at 2 16 46 pm

**Comment by alxndrkalinin** [comment]
@chartotu19 can we also rename `Raw Data` to `Data Input`

**Comment by alxndrkalinin** [comment]
@chartotu19 :
- [ ] need to restore other data input methods for presentation purposes (and keep them disabled for deployment do far)
- [ ] bottom row disappears if you switch to Data grid or if you open another tab and then come back to Get Data

**Comment by chartotu19** [comment]
@alxndrkalinin I have addressed your PR comments. The way code is written, disabled input options are hidden, not greyed out. I have enabled the remaining input options.

**Pull request merged**
