### PR TITLE
Pie chart label 

### PR DESCRIPTION
**Pull request by appletreeisyellow**

### CODE REVIEW

**Comment by alxndrkalinin** [comment]
@appletreeisyellow: These changes do not add the label behavior we discussed – they hide pie chart labels unless there is mouseover or click. Instead, labels should be always present, but they should pop out (similar how pie sectors do – increase in size) on mouseover, go back to normal on mouseleave, or stay selected on click.

**Comment by appletreeisyellow** [comment]
Alex, check this one

**Comment by alxndrkalinin** [comment]
@appletreeisyellow: I see that now sector behavior is correct, however sector labels are not emphasized on selection – can you add it so that when sector is selected it's label is also bigger in size?

**Comment by appletreeisyellow** [comment]
Ok, now pie labels are emphasized when sectors are selected.

**Comment by alxndrkalinin** [comment]
@appletreeisyellow thanks!

**Pull request merged**
